### ISSUE TITLE
polymer-platform 0.5.5 missing from NuGet repository

### ISSUE THREAD

**Issue by tdwire** [kant2002/polymer-nuget#1]
It seems that polymer-platform 0.5.5 is missing from the official NuGet repositories - when trying to install the polymer package I'm unable to install the dependency. The version that is showing up in NuGet Package Manager is 0.4.2.

**Comment by espray** [comment]
Had the same issue.

Workaround
1. Download all the `.nupkg`
2. Unzip the `.nupkg` files
3. Add the contents to your project.

`.nupkg` URLs
- https://www.nuget.org/api/v2/package/polymer/0.5.5
- https://www.nuget.org/api/v2/package/polymer-core-component-page/0.5.5
- https://www.nuget.org/api/v2/package/polymer-cyclic/0.5.5
- https://www.nuget.org/api/v2/package/polymer-core-elements/0.5.5

**Comment by kant2002** [comment]
Working on the release 1.0. closing this issue.
