### ISSUE TITLE
Update to Polymer 1.0

### ISSUE THREAD

**Issue by chapeti** [kant2002/polymer-nuget#3]
Hi guys, Polymer 1.0 is released... any chance to update the package?

**Comment by kant2002** [comment]
I currently working on it. Thanks for pointing on the release.

**Comment by kant2002** [comment]
I just update to Polymer 1.0

**Comment by rootasjey** [comment]
Hello! 
Thanks for your good work.

But I didn't manage to get it work. Do I have to import things like in a traditional browser and as it is specified in the official documentation?

NOTES: I intentionnally removed some html containers to keep the code light here.

1. I created a custom element and called it 'proto-element.html'. Then I added this code into it: 
```html
<html>
<head>
    <link rel="import"
            href="../Scripts/polymer.html">
</head>

<body>
    <script>
      // register a new element called proto-element
      Polymer({
        is: "proto-element",
        // add a callback to the element's prototype
        ready: function() {
          this.innerHTML = "I'm a proto-element. Check out my prototype!"
        }
      });
    </script>
</body>
</html>
```

2. In my HTML page (the one rendered on the device), I added this code: 

```html
<!DOCTYPE html>
<html>
<head>
    <!-- Polyfill Web Components for older browsers -->
    <script src="../../libs/webcomponents/webcomponents-lite.min.js"></script>

    <link rel="import" href="../../elements/proto-element.html">
</head>

<body>
    <proto-element></proto-element>
</body>
</html>
```

But nothing is appearing on the screen.
Can someone explain me how to get it work please?

**Comment by chapeti** [comment]
Thx Andrey !
